[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway"
buildArgs = ["GITHUB_USERNAME=$GITHUB_USERNAME", "GITHUB_TOKEN=$GITHUB_TOKEN"]

[deploy]
healthcheckPath = "/api/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

# Persistent volume for file uploads
[[deploy.volumes]]
mountPath = "/app/uploads"
name = "aslaw-uploads" 