spring:
  datasource:
    url: jdbc:postgresql://postgres.railway.internal:5432/railway
    username: postgres
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      leak-detection-threshold: 60000
      initialization-fail-timeout: 1

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        jdbc:
          time_zone: UTC

  liquibase:
    enabled: false

  web:
    resources:
      add-mappings: false
      
  mvc:
    throw-exception-if-no-handler-found: true

# Server configuration
server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

# JWT Configuration
app:
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: 86400000 # 24 hours

# Logging configuration
logging:
  level:
    com.aslaw: DEBUG
    com.infracore: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    com.zaxxer.hikari: DEBUG
    root: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized

# File upload configuration
file:
  upload:
    directory: /app/uploads
    max-size: 10MB 