spring:
  application:
    name: aslaw-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/aslaw
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    
app:
  security:
    jwt:
      secret: ${JWT_SECRET:your-secret-key-here-minimum-256-bits-for-security}
      expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.aslaw: DEBUG
    com.infracore: DEBUG
    org.springframework.security: INFO
