spring:
  application:
    name: aslaw-backend
  
  datasource:
    # Render environment variables (otomatik inject)
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5 # Free plan için optimize
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      
  jpa:
    hibernate:
      ddl-auto: validate # Production'da validate kullan
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
        format_sql: false
        
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    
  web:
    resources:
      add-mappings: false
      
  mvc:
    throw-exception-if-no-handler-found: true

# Server configuration
server:
  port: ${PORT:8080} # Render PORT environment variable
  error:
    include-message: always
    include-binding-errors: always

# Management endpoints (Health check için)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  server:
    port: ${PORT:8080}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24 hours

# File Upload Configuration
upload:
  provider: ${UPLOAD_PROVIDER:local}
  local:
    directory: ${UPLOAD_DIR:/app/uploads}
  max-file-size: 10MB
  max-request-size: 10MB

# Logging (Production optimized)
logging:
  level:
    com.aslaw: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.springframework.web: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Springdoc OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    disable-swagger-default-url: true 